# SPDX-FileCopyrightText: Chris Wilson <christopher.david.wilson@gmail.com>
#
# SPDX-License-Identifier: MIT

version = 1
SPDX-PackageName = "dotfiles"
SPDX-PackageSupplier = "Chris Wilson <christopher.david.wilson@gmail.com>"
SPDX-PackageDownloadLocation = "https://github.com/cdwilson/dotfiles/"

[[annotations]]
path = ["Library/**", "macOS/**", "dot_config/gh/config.yml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Chris Wilson <christopher.david.wilson@gmail.com>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["README.md", "README.assets/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Chris Wilson <christopher.david.wilson@gmail.com>"
SPDX-License-Identifier = "CC-BY-SA-4.0"
