# SPDX-FileCopyrightText: Chris Wilson <christopher.david.wilson@gmail.com>
#
# SPDX-License-Identifier: MIT

'$schema' = 'https://starship.rs/config-schema.json'

command_timeout = 10000

format = """
[](fg:bright-black)\
$os\
$sudo\
$username\
[](fg:bright-black bg:bright-yellow)\
$hostname\
[](fg:bright-yellow bg:yellow)\
$directory\
[](fg:yellow bg:green)\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
[](fg:green bg:blue)\
$golang\
$nodejs\
$perl\
$python\
$ruby\
$rust\
$package\
[](fg:blue bg:black)\
$docker_context\
[](fg:black bg:bright-black)\
$battery\
$time\
$cmd_duration\
[](fg:bright-black)\
$line_break\
$shlvl\
$character\
"""

# --- Left Prompt ---

# Prompt

[character]
disabled = false
format = '[$symbol ]($style)'
success_symbol = '[❯](fg:green)'
error_symbol = '[❯](fg:red)'
vimcmd_symbol = '[❮](fg:green)'
vimcmd_replace_one_symbol = '[❮](fg:purple)'
vimcmd_replace_symbol = '[❮](fg:purple)'
vimcmd_visual_symbol = '[❮](fg:yellow)'

[line_break]
disabled = false

[shlvl]
disabled = true  # Disabled because VS Code Terminal starts with a shlvl of 3
style = 'fg:white'
format = '[$symbol]($style)'
repeat = true
symbol = '❯'
repeat_offset = 1
threshold = 0

# System

[os]
disabled = false
style = 'fg:white bg:bright-black'
format = '[$symbol ]($style)'

[os.symbols]
Alpaquita = ''
Alpine = ''
AlmaLinux = ''
Amazon = ''
Android = ''
Arch = ''
Artix = ''
CentOS = ''
Debian = ''
DragonFly = ''
Emscripten = ''
EndeavourOS = ''
Fedora = ''
FreeBSD = ''
Garuda = '󰛓'
Gentoo = ''
HardenedBSD = '󰞌'
Illumos = '󰈸'
Kali = ''
Linux = ''
Mabox = ''
Macos = ''
Manjaro = ''
Mariner = ''
MidnightBSD = ''
Mint = ''
NetBSD = ''
NixOS = ''
OpenBSD = '󰈺'
openSUSE = ''
OracleLinux = '󰌷'
Pop = ''
Raspbian = ''
Redhat = ''
RedHatEnterprise = ''
RockyLinux = ''
Redox = '󰀘'
Solus = '󰠳'
SUSE = ''
Ubuntu = ''
Unknown = ''
Void = ''
Windows = '󰍲'

[sudo]
disabled = false
symbol = ''
style = 'fg:purple bg:bright-black'
format = '[$symbol ]($style)'

[username]
show_always = false
style_user = 'fg:white bg:bright-black'
style_root = 'fg:purple bg:bright-black'
format = '[($user )]($style)'

# Hostname / SSH

[hostname]
ssh_symbol = ' '
disabled = false
ssh_only = true
style = 'fg:black bg:bright-yellow'
format ='[ $ssh_symbol$hostname ]($style)'

# Path

[directory]
disabled = false
read_only = '󰌾'
read_only_style = 'fg:black bg:yellow'
style = 'fg:black bg:yellow'
format = '[ $path([ $read_only]($read_only_style)) ]($style)'
truncation_length = 3
truncation_symbol = '…/'

# SCM

## Git

[git_branch]
disabled = false
symbol = ''
only_attached = false
style = 'fg:black bg:green'
format = '[ $symbol $branch(:$remote_branch) ]($style)'

[git_commit]
disabled = false
only_detached = true
tag_disabled = false
tag_symbol = ' '
style = 'fg:black bg:green'
format = '[(\($hash $tag\) )]($style)'

[git_state]
disabled = false
style = 'fg:black bg:green'
format = '[(\($state( $progress_current/$progress_total)\) )]($style)'

[git_metrics]
disabled = true

[git_status]
disabled = false
ignore_submodules = false
style = 'fg:black bg:green'
format = '[(\[$all_status$ahead_behind\] )]($style)'

# Languages / Runtimes

[golang]
symbol = ''
style = 'fg:black bg:blue'
format = '[ $symbol( $version) ]($style)'

[nodejs]
symbol = '󰎙'
style = 'fg:black bg:blue'
format = '[ $symbol( $version) ]($style)'

[perl]
symbol = ''
style = 'fg:black bg:blue'
format = '[ $symbol( $version) ]($style)'

[python]
symbol = ''
style = 'fg:black bg:blue'
format = '[ $symbol( $version) ([](fg:purple bg:blue)[$virtualenv](fg:black bg:purple)[](fg:purple bg:blue))]($style)'

[ruby]
symbol = ''
style = 'fg:black bg:blue'
format = '[ $symbol( $version) ]($style)'

[rust]
symbol = ''
style = 'fg:black bg:blue'
format = '[ $symbol( $version) ]($style)'

# Package Version

[package]
disabled = false
symbol = '󰏗'
style = 'fg:black bg:blue'
format = '[$symbol( $version) ]($style)'

# Docker Context

[docker_context]
symbol = ''
style = 'fg:white bg:black'
format = '[ $symbol( $context) ]($style)'

# Battery

[battery]
format = '[( $symbol$percentage)]($style)'

[[battery.display]]
threshold = 10
style = 'fg:red bg:bright-black'

# Time

[time]
disabled = true
time_format = '%I:%M %p'
use_12hr = true
style = 'fg:white bg:bright-black'
format = '[(  $time)]($style)'

# Command Duration

[cmd_duration]
disabled = false
min_time = 0
style = 'fg:white bg:bright-black'
format = '[( 󰔛 $duration)]($style)'
